from src.utils.Base.BaseException import CustomBaseError


class AuthenticationError(CustomBaseError):
    pass
