from src.utils.Base.BaseException import CustomBaseError


class InvalidDataError(CustomBaseError):
    pass
