from src.utils.Base.BaseException import BaseException


class ValidationException(BaseException):
    pass
